
/**
 * Generates a README.md file for the MCP server
 */
export const generateReadme = (
  name: string,
  description: string,
  language: string,
  authType: string,
  endpoints: any[]
): string => {
  return `# ${name}

${description || 'A Model Context Protocol (MCP) server generated by MCP Server Generator.'}

## Getting Started

1. Install dependencies:
   \`\`\`
   ${language.toLowerCase() === 'python' ? 'pip install -r requirements.txt' : 'npm install'}
   \`\`\`

2. Start the server:
   \`\`\`
   ${language.toLowerCase() === 'python' ? 'python main.py' : 'npm start'}
   \`\`\`

## Available Endpoints

${endpoints.map(endpoint => `- \`${endpoint.method} ${endpoint.path}\`: ${endpoint.description}`).join('\n')}

## Authentication

${authType === 'None' 
  ? 'This server does not require authentication.' 
  : `This server uses ${authType} authentication.`}
`;
};
