// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtttswcmndibiglvhqqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dHRzd2NtbmRpYmlnbHZocXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDU2OTksImV4cCI6MjA1NzMyMTY5OX0.nRNQEVq1-9YHUj4huIgUGceMdryx1wMjyw3T9xPvHJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);